feat: provide initial browser test data automatically
City-of-Helsinki/kukkuu pull request #395
Opened 2024-07-12 15:54 UTC by nikomakela

KK-1168.

Create Group, ADGroup, and Project resources for browser tests. This is done in the project app's ready-function and with a post_migrate -signal.

In Django, the post_migrate signal is emitted in the following scenarios:

After Migrations: It is triggered immediately after Django successfully applies migrations to your database. This includes both initial migrations when setting up your project and subsequent migrations when you make changes to your models.

During Tests (with --keepdb): If you run your Django tests with the --keepdb flag, the post_migrate signal will also be triggered after the test database is initialized. However, if you use a separate test database for each test case, the signal might be emitted for each test.

Management Commands: Some Django management commands, like createsuperuser, might also trigger the post_migrate signal if migrations need to be applied beforehand.

2024-07-12 16:03 UTC, terovirtanen commented
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr395.api.dev.hel.ninja** :rocket::rocket::rocket:

2024-07-12 16:05 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kukkuu-pr395.api.dev.hel.ninja :laughing::tada::tada::tada:

2024-07-26 08:32 UTC, karisal-anders commented
`docker compose up --build` **failed** with this PR's branch when run locally:
```bash
$ docker compose up --build
time="2024-07-26T11:28:46+03:00" level=warning msg="City-of-Helsinki\\kukkuu\\docker-compose.yml: `version` is obsolete"
[+] Running 14/14
 ✔ postgres Pulled                                                                                                               9.6s
   ✔ bff3e048017e Pull complete                                                                                                  3.1s
   ✔ e3e180bf7c2b Pull complete                                                                                                  3.2s
   ✔ 62eff3cc0cff Pull complete                                                                                                  3.3s
   ✔ 3d90a128d4ff Pull complete                                                                                                  3.3s
   ✔ ba4ce0c5ab29 Pull complete                                                                                                  3.6s
   ✔ a8f4b87076a9 Pull complete                                                                                                  3.7s
   ✔ 4b437d281a7e Pull complete                                                                                                  3.7s
   ✔ f1841d9dcb17 Pull complete                                                                                                  3.8s
   ✔ bf897300657d Pull complete                                                                                                  7.1s
   ✔ 3bfdfb831df4 Pull complete                                                                                                  7.1s
   ✔ c44ac1fcc543 Pull complete                                                                                                  7.2s
   ✔ 9ad3441d354a Pull complete                                                                                                  7.2s
   ✔ 2d79312566dd Pull complete                                                                                                  7.2s
[+] Building 22.1s (15/15) FINISHED                                                                              docker:desktop-linux
 => [django internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 1.28kB                                                                                           0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                   0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 23)                                                  0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 37)                                                  0.0s
 => [django internal] load metadata for registry.access.redhat.com/ubi9/python-39:latest                                         0.3s
 => [django internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                                  0.0s
 => [django appbase 1/7] FROM registry.access.redhat.com/ubi9/python-39:latest@sha256:01c9e53b32acd96f9fe7781727140df6868c91ebc  0.0s
 => [django internal] load build context                                                                                         3.0s
 => => transferring context: 10.02MB                                                                                             2.6s
 => CACHED [django appbase 2/7] WORKDIR /app                                                                                     0.0s
 => CACHED [django appbase 3/7] RUN mkdir /entrypoint                                                                            0.0s
 => CACHED [django appbase 4/7] COPY --chown=default:root requirements.txt /app/requirements.txt                                 0.0s
 => CACHED [django appbase 5/7] COPY --chown=default:root requirements-prod.txt /app/requirements-prod.txt                       0.0s
 => CACHED [django appbase 6/7] RUN yum update -y && yum install -y     nc     && pip install -U pip     && pip install --no-ca  0.0s
 => CACHED [django appbase 7/7] COPY --chown=default:root docker-entrypoint.sh /entrypoint/docker-entrypoint.sh                  0.0s
 => CACHED [django development 1/3] COPY --chown=default:root requirements-dev.txt /app/requirements-dev.txt                     0.0s
 => CACHED [django development 2/3] RUN pip install --no-cache-dir -r /app/requirements-dev.txt                                  0.1s
 => [django development 3/3] COPY --chown=default:root . /app/                                                                   0.6s
 => [django] exporting to image                                                                                                  0.4s
 => => exporting layers                                                                                                          0.3s
 => => writing image sha256:8e679b9dd780dc545de9c3f57f2308f49573d4eb7fef73e82846c4e1b63e57a1                                     0.0s
 => => naming to docker.io/library/kukkuu-django                                                                                 0.0s
[+] Running 4/4
 ✔ Network helsinki          Created                                                                                             0.0s
 ✔ Volume "kukkuu_pgdata"    Created                                                                                             0.0s
 ✔ Container kukkuu-db       Created                                                                                             0.2s
 ✔ Container kukkuu-backend  Created                                                                                             0.1s
Attaching to kukkuu-backend, kukkuu-db
kukkuu-db       | The files belonging to this database system will be owned by user "postgres".
kukkuu-db       | This user must also own the server process.
kukkuu-db       |
kukkuu-db       | The database cluster will be initialized with locale "en_US.utf8".
kukkuu-db       | The default database encoding has accordingly been set to "UTF8".
kukkuu-db       | The default text search configuration will be set to "english".
kukkuu-db       |
kukkuu-db       | Data page checksums are disabled.
kukkuu-db       |
kukkuu-db       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
kukkuu-db       | creating subdirectories ... ok
kukkuu-db       | selecting default max_connections ... 100
kukkuu-db       | selecting default shared_buffers ... 128MB
kukkuu-db       | selecting default timezone ... Etc/UTC
kukkuu-db       | selecting dynamic shared memory implementation ... posix
kukkuu-db       | creating configuration files ... ok
kukkuu-db       | running bootstrap script ... ok
kukkuu-db       | performing post-bootstrap initialization ... ok
kukkuu-backend  | Ncat: Version 7.92 ( https://nmap.org/ncat )
kukkuu-backend  | Ncat: Connection refused.
kukkuu-backend  | Waiting for postgres database connection...
kukkuu-db       |
kukkuu-db       | WARNING: enabling "trust" authentication for local connections
kukkuu-db       | You can change this by editing pg_hba.conf or using the option -A, or
kukkuu-db       | --auth-local and --auth-host, the next time you run initdb.
kukkuu-db       | syncing data to disk ... ok
kukkuu-db       |
kukkuu-db       | Success. You can now start the database server using:
kukkuu-db       |
kukkuu-db       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
kukkuu-db       |
kukkuu-db       | waiting for server to start....2024-07-26 08:29:20.848 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
kukkuu-db       | 2024 [...]

2024-07-26 08:37 UTC, karisal-anders requested changes
`docker compose up --build` doesn't work now locally, see [comment](https://github.com/City-of-Helsinki/kukkuu/pull/395#issuecomment-2252242013)

2024-08-23 08:48 UTC, nikomakela commented
> `docker compose up --build` doesn't work now locally, see [comment](https://github.com/City-of-Helsinki/kukkuu/pull/395#issuecomment-2252242013)

It does work for me. I tested several times:
1. docker compose down
2. docker compose up --build

2024-08-23 08:58 UTC, terovirtanen commented
**KUKKUU-API branch is deployed to platta: https://kukkuu-pr395.api.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-23 09:00 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kukkuu-pr395.api.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-23 09:29 UTC, karisal-anders commented
> > `docker compose up --build` doesn't work now locally, see [comment](https://github.com/City-of-Helsinki/kukkuu/pull/395#issuecomment-2252242013)
> 
> It does work for me. I tested several times:
> 
> 1. docker compose down
> 2. docker compose up --build
> 
> And it does also work through the deployment pipeline.

Have you tried with destroying the used volume?

2024-08-23 10:22 UTC, nikomakela commented
> > > `docker compose up --build` doesn't work now locally, see [comment](https://github.com/City-of-Helsinki/kukkuu/pull/395#issuecomment-2252242013)
> > 
> > 
> > It does work for me. I tested several times:
> > 
> > 1. docker compose down
> > 2. docker compose up --build
> > 
> > And it does also work through the deployment pipeline.
> 
> Have you tried with destroying the used volume?

Yep, I had all the migrations not ran. Also, the review environment should not have anything existing and it still succeeds. 🤔

2024-08-23 13:06 UTC, merged